version: "3"
services:
  vaultwarden:
    container_name: vaultwarden
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ROCKET_ENV=staging
      - ROCKET_PORT=80
      - ROCKET_WORKERS=10
      - SIGNUPS_ALLOWED=false # True only when adding new users
      #- ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=587
      - SMTP_SSL=true
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - DOMAIN=${DOMAIN}
    image: vaultwarden/server:latest
    #ipc: shareable
    ports:
      - ${PORT}:80/tcp
    restart: unless-stopped
    volumes:
      - ${DATA}:/data
